### ISSUE TITLE
Issue with TYPO3 v11 and PHP 8.1

### ISSUE THREAD

**Issue by devtroll** [invokablegmbh/jar_pretty_preview#1]
Installing over composer is not possible, because of 2 warnings:

> Warning: Undefined array key "pretty_preview_content" in /var/www/html/public/typo3conf/ext/jar_pretty_preview/ext_localconf.php line 6 

> Warning: Undefined array key "fluidBasedPageModule" in /var/www/html/public/typo3conf/ext/jar_pretty_preview/ext_tables.php line 15 

I make an pull request for fix.

**Comment by invokablegmbh** [comment]
It's implemented in v1.0.14, thanks a lot!
